```{r}
library(httr)
```

# 輸入 ChatGPT API金鑰
```{r}
chatGPT_API <- "YOUR-API-KEY"
```

# GPT 版本
```{r}
model="gpt-3.5-turbo-0301"
```

# 指令
```{r}
prompt_content<-"You are a political figure's aide, analyzing the policy proposals of an electoral opponent. Extract one to three objects from the following text in Traditional Chinese, and separate them with commas. Do not provide additional explanations. If unable to analyze, respond with 'don't know."
```

# 以下做法是將 API 回傳的結果存回原本文件中的新增欄位。請按照你的文件名跟欄位名，在以下註解標記處修改：
* 文件名 legi_politic
* 要替換的文本欄位 content
* 新增欄位名 chatgpt
```{r}
# 改成你的文件名跟新增欄位名
legi_politic$chatgpt<-""

for(q in 1:nrow(legi_politic)){  #替換文件名
  print(q)
chatGPT_response <- POST(
  url = "https://api.openai.com/v1/chat/completions",
  add_headers(Authorization = paste("Bearer", chatGPT_API)),
  content_type_json(),
  encode = "json",
  body = list(
    model = model,
    messages = list(list(role = "user", content = paste0(prompt_content,legi_politic$content[q]))), # 記得替換文件名和要替換的文本欄位
    temperature = 0  # 在這裡設定 temperature 為 0
  )
)

result <- content(chatGPT_response)$choices[[1]]$message$content

legi_politic$chatgpt[q] <- result  # 記得替換文件名
}
```
